---
- import_tasks: tasks/docker-deb.yml

- name: Cluster user
  user:
    name: cluster
    shell: /bin/bash
    groups: sudo,docker
    append: yes

- name: Cluster opt permissions
  file:
    path: /opt
    owner: cluster

- name: Cluster repo
  become: true
  become_user: cluster
  git:
    repo: https://github.com/liquidinvestigations/cluster
    dest: /opt/cluster
    version: master

- name: Cluster ini
  become: true
  become_user: cluster
  template:
    src: cluster.ini
    dest: /opt/cluster/cluster.ini

- name: Cluster container
  become: true
  become_user: cluster
  shell: |
    set -ex
    id
    /opt/cluster/bin/docker.sh
    docker exec cluster ./cluster.py wait
  args:
    creates: /opt/cluster/etc/supervisord.conf
